// SPDX-FileCopyrightText: 2026 Sebastien Rousseau <sebastian.rousseau@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//go:build ignore

// specgen writes the published JSON Schema of the attestation from the Go
// types that implement it, and with -check fails when the committed file has
// drifted.
//
// A hand-written schema beside the Go types would be a second copy that
// disagrees the first time a field is added, so the schema is derived from
// attestation.Statement by reflection. The scoring rubric is not here: it is
// generated from scout's scorer, in scout, because the scorer is the thing it
// must never disagree with.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"time"

	"github.com/sebastienrousseau/scout-reporting/attestation"
)

const (
	schemaPath = "spec/attestation/mcp-evaluation-v1.schema.json"
	// comment travels in the file, because JSON has no other place for it.
	comment = "Generated by scripts/specgen from the scout-reporting source; do not edit. " +
		"Licensed Apache-2.0 (see REUSE.toml)."
)

func main() {
	verify := len(os.Args) > 1 && os.Args[1] == "-check"

	want, err := render(schema())
	if err != nil {
		fail(err)
	}
	if verify {
		got, err := os.ReadFile(schemaPath)
		if err != nil || !bytes.Equal(got, want) {
			fmt.Fprintf(os.Stderr, "specgen: %s out of date with the source; run make spec\n", schemaPath)
			os.Exit(1)
		}
		fmt.Println("specgen: the published schema matches the source")
		return
	}
	if err := os.MkdirAll(filepath.Dir(schemaPath), 0o755); err != nil { // #nosec G301 -- a docs directory
		fail(err)
	}
	if err := os.WriteFile(schemaPath, want, 0o644); err != nil { // #nosec G306 -- a published file
		fail(err)
	}
	fmt.Printf("specgen: wrote %s\n", schemaPath)
}

// render is deterministic: encoding/json sorts map keys, and the trailing
// newline makes the file a well-formed text file for every tool that cares.
func render(v any) ([]byte, error) {
	b, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(b, '\n'), nil
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "specgen:", err)
	os.Exit(1)
}

// fixed overrides the reflected schema for the fields whose value is a
// constant or an enumeration. Reflection sees a string; the format sees a
// fixed URI or a closed set, and a consumer validating against the schema
// should be told, so the schema says what a valid statement must carry
// rather than only its shape.
var fixed = map[string]map[string]any{
	"Statement":  {"_type": map[string]any{"const": attestation.StatementType}, "predicateType": map[string]any{"const": attestation.PredicateType}},
	"Evaluation": {"subjectKind": map[string]any{"const": attestation.SubjectKindDescriptor}},
	"Target":     {"transport": map[string]any{"type": "string", "enum": []string{"http", "stdio"}}},
	"Verdict":    {"status": map[string]any{"type": "string", "enum": []string{"pass", "warn", "fail", "skip", "info"}}},
}

// schema describes attestation.Statement as JSON Schema 2020-12.
func schema() any {
	defs := map[string]any{}
	root := typeSchema(reflect.TypeOf(attestation.Statement{}), defs)
	return map[string]any{
		"$schema":  "https://json-schema.org/draft/2020-12/schema",
		"$id":      attestation.PredicateType + "/schema.json",
		"$comment": comment,
		"title":    "scout MCP evaluation attestation (in-toto Statement, predicate v1)",
		"$ref":     root["$ref"],
		"$defs":    defs,
	}
}

var timeType = reflect.TypeOf(time.Time{})

func typeSchema(t reflect.Type, defs map[string]any) map[string]any {
	for t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	if t == timeType {
		return map[string]any{"type": "string", "format": "date-time"}
	}
	switch t.Kind() {
	case reflect.String:
		return map[string]any{"type": "string"}
	case reflect.Bool:
		return map[string]any{"type": "boolean"}
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return map[string]any{"type": "integer"}
	case reflect.Float32, reflect.Float64:
		return map[string]any{"type": "number"}
	case reflect.Slice, reflect.Array:
		return map[string]any{"type": "array", "items": typeSchema(t.Elem(), defs)}
	case reflect.Map:
		return map[string]any{"type": "object", "additionalProperties": typeSchema(t.Elem(), defs)}
	case reflect.Struct:
		name := t.Name()
		if _, done := defs[name]; !done {
			defs[name] = nil // reserve, so a recursive type terminates
			props := map[string]any{}
			var required []string
			for i := 0; i < t.NumField(); i++ {
				f := t.Field(i)
				if !f.IsExported() {
					continue
				}
				tag := f.Tag.Get("json")
				jname, opts, _ := strings.Cut(tag, ",")
				if jname == "-" {
					continue
				}
				if jname == "" {
					jname = f.Name
				}
				if v, ok := fixed[name][jname]; ok {
					props[jname] = v
				} else {
					props[jname] = typeSchema(f.Type, defs)
				}
				if !strings.Contains(opts, "omitempty") {
					required = append(required, jname)
				}
			}
			def := map[string]any{"type": "object", "properties": props}
			if len(required) > 0 {
				def["required"] = required
			}
			defs[name] = def
		}
		return map[string]any{"$ref": "#/$defs/" + name}
	}
	fail(fmt.Errorf("no schema mapping for %s", t))
	return nil
}
